### PR TITLE
Clarification on discovery process

### PR DESCRIPTION
**Pull request by arnoldblinn**

### CODE REVIEW

**Comment by pawel-kow** [comment]
Just an idea, so that developer teams do not overlook that, to have a table with return codes, same as in 4.3.5?

Probably same can apply to 4.2.1.

**Comment by arnoldblinn** [comment]
Good call. On it.

**Comment by arnoldblinn** [comment]
@pawel-kow Submitted.  The only one "vague" is the API to get an access token.  A 200 indicates success, but we've never had the need to be detailed on error responses here. So I left that one vague.  But I do like adding explicit tables for all the API calls with responses.....

**Comment by pawel-kow** [comment]
Looks good.

**Pull request merged**
